services:
  web:
    image: ghcr.io/foxinuni/quickpass-backend:main
    restart: unless-stopped
    environment:
      LISTEN_ADDRESS: ":3000"
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      CACHE_URL: redis://redis:6379/0
      MIGRATIONS_SRC: "file://migrations"
      JWT_SECRET: secret
      SENDGRID_EMAIL: me@example.com
      SENDGRID_API_KEY: something something
    ports:
      - "8000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  redis:
    image: redis
    ports:
      - "6379:6379"
  